# Default (double-click / run.cmd). Client profile.
# NOT hidden-service (-H). DNS on 127.0.0.1:53.
# ifaddr 10.192.0.1/16 + fd2e:7365:7368::1/64.
# SNAPP host is session-router.snapp.ini / run-snapp.cmd.
#
[router]
# Configuration for routing activity.


# Network ID; this is 'session-router' for mainnet, 'testnet' for testnet.
#netid=session-router

# Directory in which to store Session Router runtime data such as router contact info
# and connection data. If not specified, the default is to use the directory containing
# the config file specified when starting Session Router.
data-dir=data


[exit]


# Specify an optional authentication token required to use a non-public exit node.
# For example:
# auth=myfavouriteexit.sesh:abc
# uses the authentication code `abc` whenever myfavouriteexit.sesh is accessed.
# Can be specified multiple times to store codes for different exit nodes. The
#.sesh name may also be replaced with a.loki ONS name.
#auth=

# Enable exit-node functionality for local Session Router instance.
enable=false

# Specifies the IP traffic accepted by the local exit node traffic policy. If any are
# specified then only matched traffic will be allowed and all other traffic will be
# dropped. Examples:
# policy=tcp
# would allow all TCP/IP packets (regardless of port);
# policy=0x69
# would allow IP traffic with IP protocol 0x69;
# policy=udp/53
# would allow UDP port 53; and
# policy=tcp/smtp
# would allow TCP traffic on the standard smtp port (21).
#policy=

# Reserve an ip range to use as an exit broker for a `.sesh` address
# Specify a `.sesh` address and a reserved ip range to use as an exit broker.
# Examples:
# reserved-range=whatever.sesh
# would route all exit traffic through whatever.sesh; and
# reserved-range=stuff.sesh:100.0.0.0/24
# would route the IP range 100.0.0.0/24 through stuff.sesh.
# This option can be specified multiple times (to map different IP ranges).
#reserved-range=

# Advertise that exit node routes exit traffic to the specified IP range. If omitted, the
# default is ALL public ranges. Can be set to public to indicate that this exit
# routes traffic to the public internet.
# For example:
# routed-range=10.0.0.0/16
# routed-range=public
# to advertise that this exit routes traffic to both the public internet, and to
# 10.0.x.y addresses.
# 
# Note that this option does not automatically configure network routing; that
# must be configured separately on the exit system to handle Session Router traffic.
#routed-range=


[network]
ifaddr=10.192.0.1/16
ifaddr=fd2e:7365:7368::1/64
# Network settings related to network devices and communications.


# Filename of a persistent, private key to use on the network. If not specified a
# different random address will be used each time Session Router restarts.
# 
# The session-router-config program can be used to generate such a key file.
#keyfile=

# Set the endpoint authentication type.
# none/whitelist/lmq/file
#auth-type=

# OMQ endpoint to talk to for authenticating new sessions
# ipc:///var/lib/session-router/auth.socket
# tcp://127.0.0.1:5555
#omq-auth-endpoint=

# OMQ function to call for authenticating new sessions
# session-router.auth
#omq-auth-method=session-router.auth

# Manually add a remote endpoint by PUBKEY.sesh address to the access whitelist.
#auth-whitelist=

# Read auth tokens from file to accept endpoint auth
# Can be provided multiple times
#auth-file=

# How to interpret the contents of an auth file.
# Possible values: plaintext
#auth-file-type=

# Manually add a static auth code to accept for endpoint auth
# Can be provided multiple times
#auth-static=

# Determines whether we will pubish our service's ClientContact to the network (client default: TRUE)
#reachable=true

# Enable / disable automatic route configuration.
# When this is enabled and an exit is used Session Router will automatically configure the
# operating system routes to route public internet traffic through the exit node.
# This is enabled by default, but can be disabled if advanced/manual exit routing
# configuration is desired.
#auto-routing=true

# Enable / disable route configuration blackholes.
# When enabled Session Router will drop IPv4 and IPv6 traffic (when in exit mode) that is not
# handled in the exit configuration. Enabled by default.
#blackhole-routes=true

# Interface name for Session Router traffic. If unset Session Router will look for a free name
# matching 'sr-tunN', starting at N=0 (e.g. sr-tun0, sr-tun1,...) for clients; relays default
# to sr-tun@XXXXXXXX where XXXXXXXX is the first 8 hex digits of the Session node pubkey.
ifname=sr-tun0

# Private IP and netmask to use to map Session Router traffic to local addresses.
# 
# The IPs (one IPv4, one IPv6) given here will be the IPs that remote Session
# Router clients will access if attempting to establish connections to this
# Session Router instance, and the remainder of the IP range will be the addresses
# that this Session Router uses to send traffic to remote relay and client peers.
# That is, a remote client attempting to connect to you through Session Router
# will be tunneled to the IPv4 or IPv6 address specified here.
# 
# For example, 172.16.0.1/16 will use 172.16.0.1 for this Session Router
# instance's IPv4 address and 172.16.x.y will be used to map connections to remote
# peer addresses. For IPv6, fd2e:7365:7368::1/64 will use fd2e:7365:7368::1 for
# this Session Router instance, and will map other remotes to addresses in
# fd2e:7365:7368:0:w:x:y:z. (These two ranges are the defaults if not specified
# *and* they are not already in use on the system).
# 
# This option can be given twice: once to set an IPv4 address and range, and once
# to set an IPv6 address and range. If one or the other is omitted then an unused
# private range (/16 for IPv4, and /64 for IPv6) will be automatically detected
# and used.
# 
# An "all-zero" address can be used with a custom netmask to use auto-detection
# with a custom size: for instance "0.0.0.0/10" will auto-detect an unused /10
# IPv4 private address range, and "::/56" would look for an unused /56 IPv6
# address range.
# 
# If you intend to run network daemons for others to connect to (for example
# HTTP), then it is recommended that you specify explicit IPv4 and IPv6 addresses
# here and set up network servers (such as nginx to serve HTTP traffic) to listen
# on those two addresses. If you are only using Session Router to connect to
# remote instances then you can typically leave this blank to auto-select an
# unused network range.
# Map a remote `.sesh` or `.snode` address to always use a fixed local IPv4, IPv6, or both
# (separated by a comma). For example:
# mapaddr=kcpyawm9se7trdbzncimdi5t7st4p5mh9i1mg7gkpuubi4k4ku1y.snode:172.16.0.42,fd2e:7365:7368::42
# mapaddr=55fxrybf3jtausbnmxpgwcsz9t8qkf5pr8t5f4xyto4omjrkorpy.snode:fd2e:7365:7368::deca:f20
# reserves the given IPv4/IPv6 address for the indicated pubkeys.
# 
# Session Router addresses that are *not* explicitly mapped will use the next available unused IP
# (for IPv4), or a pubkey-derived address with fallback to next available address for IPv6.
# 
# The given IP address(es) must be inside the ranges configured by ifaddr=, and ONS addresses
# cannot be used.
#mapaddr=

# This controls how many recently expired connection addresses to remember: if a connection
# closed or expires then the assigned addresses are remembered in this cache and will be reserved
# and reused if the connection is reestablished while still in the cache. This setting controls
# the maximum number of such addresses Session Router will remember.
# 
# This cache does not persist across restarts: if you want a particular client to have a persistent
# address, use the mapaddr= setting instead.
#expired-address-cache=1000

# Specify SRV Records for services hosted on the SNApp for protocols that use SRV
# records for service discovery. Each line specifies a single SRV record as:
# srv=_service._protocol priority weight port target.sesh
# and can be specified multiple times as needed. If `target.sesh` is set to
# `localhost.sesh` it will be replaced with this Session Router's address.
# 
# For more info see
# https://docs.oxen.io/products-built-on-oxen/session-router/snapps/hosting-snapps
# and general description of DNS SRV record configuration.
#srv=


[paths]
# Settings related to path selection such as number of hops and selection criteria


# Minimum number of routers Session Router client will attempt to maintain direct (i.e. "edge")
# connections to. All paths will start through one of these edges.
# 
# Session Router may use more than this number of edges in single-hop connection mode
# (see [paths]:client-hops) and may use fewer connections if limited by [paths]:strict-edge.
#edge-connections=4

# Number of paths to maintain per active outbound connection to a remote client or relay.
# Only one path is actively used at a time, but others are used for regular path rotation
# and as a fallback for path failure.
# 
# Note that this value applies to EACH outbound connection separately: if you have active
# connections to 5 clients and 3 snodes, Session Router will maintain 16 outbound paths (at
# the default setting of 2).
# 
# Setting this value to 1 is allowed, but will result in brief periods of packet loss
# whenever paths expire due to the lack of allowed backup path.
#outbound-paths=2

# Number of hops to use when establishing a connection to a service node relay to
# communicate through that relay to another client.
# 
# The overall number of hops to the remote client is this value PLUS the number of inbound
# hops the other client has configured for their inbound hops (via [paths]:inbound-hops).
# 
# Setting this value to 1 puts Session Router into single-hop mode for the connection from this
# client to the aligned pivot router, which potentially weakens connection privacy as
# your public IP will be observable to any service node listed as a pivot for any remote
# client that you connect to.
#client-hops=3

# Number of hops to use when establishing a connection to talk to a service node.
# 
# A value of 1 results in establishing direct connection to the snode (i.e. only
# encryption but no onion routing); 2 would select one intermediate snode to onion
# route through; 4 uses three intermediates, and so on, up to the maximum of 8.
# 
# Additional hops increases privacy but also increase latency and reduces network
# performance through the path.
# 
# If not set, this default to one greater than the value of [paths]:client-hops.
# 
# Setting this value to 1 puts Session Router into single-hop mode for the connection from this
# client to service node (i.e. `.snode` addresses) which potentially weakens connection
# privacy as any service nodes you connect to will be able to observe your public IP.
#relay-hops=

# Number of local paths that Session Router maintains for both network reachability (i.e. remote
# clients connecting to this instance) and network communication such as looking up
# client records and updating network state
# 
# This value does NOT apply to paths that are built to reach external clients or relays.
#inbound-paths=4

# Number of hops to use for inbound and general request connections (see [paths]:inbound-paths).
# 
# When a remote Session Router is connecting to this instance, this controls the path length of the
# local side of the full client-to-client path (i.e. from the common relay "pivot" to this
# Session Router instance).
# 
# If not set, this value defaults to the same value as [paths]:client-hops.
#inbound-hops=

# This configures the maximum number of times a single relay may be used as a path pivot.
# The default is one, meaning each inbound path is built to a distinct pivot, but special
# cases (such as a one-hop reachable endpoint using a small number of pivots) may want to
# increase this to allow multiple pivots to be used at once. Leaving this at the default
# of 1 is recommended for most cases.
#inbound-pivot-reuse=1

# Netmask for router path selection; each router must be from a distinct IPv4 subnet
# of the given size. Defaults to 24.
# 
# For instance, setting this to 16 selects routers for each path that have distinct
# x.y.*.* IP addresses; 32 merely requires that each router have a unique IP. Setting
# this to 0 disables IP uniqueness entirely (i.e. paths can be selected that go through
# different Session Router routers on the same IP)
#unique-range-size=24

# The minimum expiry time a path/pivot must have for it to be eligible when switching
# to a new path. Inactive paths older than this will be replaced with new paths.
#acceptable-expiry=300s

# The minimum allowed path/pivot expiry time (in seconds) of a currently active outbound path.
# When an active path reaches an expiry less than this value then the path to the remote will
# be rotated immediately to use a newer path.
# 
# This value cannot be larger than acceptable-expiry.
#min-expiry=60s

# How long to wait for a session or path to establish before timing out the attempt.
# Value is in seconds, or milliseconds with an ms suffix (e.g. 2500ms).
#build-timeout=10000ms

# How frequently to send pings along built paths to test that they are still alive.
#ping-interval=5s

# The maximum number of consecutive missed pings (see ping-interval) allowed for a path. If a path
# misses more than this, the path will be considered to have died and be replaced.
#max-missed-pings=5

# List of service node public keys of "edge" nodes (also known as "first hops") that
# Session Router will exclusively use when establishing paths through the network. You can use
# this to always use closer (i.e. lower latency) first hops, or to limit which network
# nodes see connections from your IP address.
# 
# Public keys can be provided either in native Session Router address format (ADDR.snode), or using
# the 64-character hexademical pubkey notation common used for Session service nodes.
# Specify this option multiple times to specify multiple allowed edge nodes.
# 
# Note that only registered service node pubkeys will be used, and so connectivity will be
# lost entirely if all of the listed pubkeys are or become deregistered.
# 
# This option is incompatible with single-hop outbound path mode (see `[paths]:client-hops`
# and `[paths]:relay-hops`).
# 
# Note that if bootstrapping is needed a connection will be made to the configured bootstrap
# nodes to obtain an initial router list. See [bootstrap]:add-node if you want to also
# override the nodes used for bootstrapping.
#strict-edge=

# Adds a Session Router relay `.snode` address to the list of relays to avoid when
# connecting to edges or building paths. Can be specified multiple times.
#blacklist-snode=


[dns]
# DNS configuration


# Address(es) on which to listen for DNS requests. This can either be an IP address
# (to use the default DNS port 53) or an IP followed by `:port' to listen on a custom
# port. To specify an IPv6 address, surround the address with '[' and ']'.
# 
# This option can be specified multiple times to bind to multiple addresses.
# 
# If this Session Router instance has no need to establish outbound connection (for example,
# for a hidden service) then this can be set to an empty string to disable the DNS listener
# entirely. WARNING: disabling this makes it impossible to make new outbound connections!
listen=127.0.0.1:53
# Upstream resolver(s) to use as fallback for non-Session Router addresses.
# Multiple values accepted. Can be set to empty to disable upstream DNS resolution
# for advanced setups.
# 
# If not specified, the default is to use Quad9 public DNS servers (https://quad9.net).
#upstream=9.9.9.9
#upstream=149.112.112.112
#upstream=[2620:fe::fe]
#upstream=[2620:fe::9]

# This option can be used to supply custom options to libunbound, which is used
# internally when DNS requests are made that are not for a.sesh/.snode address.
# 
# To add a custom option specify this option with a value of `unbound-option-name: value`;
# for example, to limit the maximum record cache time:
# unbound=cache-max-ttl: 3600
# Or to enable DNSSEC validation:
# unbound=trust-anchor-file: /path/to/dns/root.key
# 
# You can use this option multiple times to specify more unbound options.
# 
# See https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html
# for all supported unbound options.
#unbound=

# Configures unbound to use the given `hosts' files when resolving addresses. Can be
# used to add custom addresses or perform client-side DNS filtering. If omitted or set
# to the string 'SYSTEM' then the system default (/etc/hosts, or WINDIR/etc/hosts on
# Windows) will be used. Can be set to an empty string to not add any hosts file.
#unbound-hosts=SYSTEM

# Can be uncommented and set to 1 to disable resolvconf configuration of Session Router DNS.
# (This is not used directly by Session Router itself, but by the Session Router init scripts
# on systems which use resolveconf)
#no-resolvconf=


[bind]
listen=:1191
# This section allows specifying the IP that Session Router uses for incoming and outgoing
# connections. For simple setups it can usually be left blank, but may be required
# for relays with multiple IP address, or relays that listen on a private IP with
# forwarded public traffic.


# IP and/or port for Session Router to use for connections to relays.
# 
# Defaults to ':1091', which means to use port 1091 on any available address.
# 
# Examples:
# listen=15.5.29.5:1099 -- uses a specific IP and port
# listen=10.0.2.2 -- uses a specific IP, default port (1191)
# listen=:1234 -- uses any IP, port 1234
#listen=


[api]
enabled=true
#bind=stripped
# JSON API settings


# Determines whether or not the OMQ JSON API is enabled. By default this is enabled for clients, disabled for relays
#enabled=true

# IP addresses and ports to bind to.
# Recommend localhost-only for security purposes.
#bind=tcp://127.0.0.1:1190


[bootstrap]
add-node=bootstrap.signed
# Configure nodes that will bootstrap us onto the network


# Specify a bootstrap file containing a list of signed RelayContacts of service nodes
# which can act as a bootstrap. Can be specified multiple times. If set this overrides
# the built-in seed node list.
#add-node=


[logging]
type=file
file=session-router.log
# Logging settings


# Log type (format). Valid options are:
# print - print logs to standard output
# system - logs directed to the system logger (syslog/eventlog/etc.)
# file - plaintext formatting to a file
# 
#type=print

# Minimum log severity level to print. Logging below this level will be ignored.
# Can also be set to a comma-separated list of individual categories, such as:
# *=warn, logcat123=debug
# 
# Valid log levels, in ascending order, are:
# trace, debug, info, warn, error, critical, off
#level=info

# When using type=file this is the output filename.
#file=
