[DEFAULT]
upstream-branch = stable
debian-branch = ubuntu/stonking
upstream-tag = v%(version)s

[buildpackage]
submodules = true
ignore-new = true
pbuilder = true
dist = stonking


[pq]
ignore-new = true
